### ISSUE TITLE
Display stats to Users

### ISSUE THREAD

**Issue by BacLuc** [sopra-fs22-group-36/screw-your-neighbor-server#15]
As a registered player,I can log in to keep track of my game performance.

- [ ] Besides the registration button, there is also a login button. https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/issues/92
- [ ] This button takes the user to a page where he can log-in using his username and password (under condition he has previously registered for a user account). https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/issues/93
- [ ] On the main user page is button to see my performance. https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/152 & https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/issues/94
- [ ] When the player is logged in, he has the option of clicking on his profile which opens a window that lets him see his game performance (minimum: Games won, games lost) and important account information (minimum: username and Creation date).https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/issues/94

**Comment by elBeato** [comment]
Depends on closing userstory #14 this one is obsolet. 

## Information to #14
We are closing this issue without an implementation. The reasons are varied:

    No added value for the fun of the game
    Heroku does not have a persistent DB
    All common games in this form are played without registration.
    We have already implemented user account login and registration in M1.
    Low priority

It took place in consultation with our TA.
