### ISSUE TITLE
M4: Report, README, License

### ISSUE THREAD

**Issue by BacLuc** [sopra-fs22-group-36/screw-your-neighbor-server#182]
- [x] Write Report
  - [x] In your report, reflect on challenges (technical, planning, coordination) you were facing in the last
months. What did you learn? What would you do differently next time? What helped your team
work well together? Compile the challenges to a short list (bullet points are enough).
The report should be submitted as a PDF to OLAT with a name of form FS22-Group-XX-M4-
Report.pdf by the group leader. Please make sure the title page contains the group name, group
leader, and information about all group members (name and matriculation number). In the report,
briefly introduce your project and its motivation/purpose, provide screenshots of your applica-
tion (including captions), and compile the learnings and challenges as a bullet-point list.

- [x] Add README to server
**Introduction**: the project’s goal and motivation.
**Technologies** used (short).
**High-level components**: Identify your project’s 3-5 main components. What is their role?
How are they correlated? Reference the main class, file, or function in the README text
with a link.
**Launch & Deployment**: Write down the steps a new developer joining your team would
have to take to get started with your application. What commands are required to build and
run your project locally? How can they run the tests? Do you have external dependencies
or a database that needs to be running? How can they do releases?
Illustrations: In your client repository, briefly describe and illustrate the main user flow(s)
of your interface. How does it work (without going into too much detail)? Feel free to
include a few screenshots of your application.
**Roadmap**: The top 2-3 features that new developers who want to contribute to your project
could add.
**Authors and acknowledgment.**

- [x] Add README to react
**Introduction**: the project’s goal and motivation.
**Technologies** used (short).
**High-level components**: Identify your project’s 3-5 main components. What is their role?
How are they correlated? Reference the main class, file, or function in the README text
with a link.
**Launch & Deployment**: Write down the steps a new developer joining your team would
have to take to get started with your application. What commands are required to build and
run your project locally? How can they run the tests? Do you have external dependencies
or a database that needs to be running? How can they do releases?
Illustrations: In your client repository, briefly describe and illustrate the main user flow(s)
of your interface. How does it work (without going into too much detail)? Feel free to
include a few screenshots of your application.
**Roadmap**: The top 2-3 features that new developers who want to contribute to your project
could add.
**Authors and acknowledgment.**
